[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "reproducible-ml-workflows"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks.install-requirements]
cmd = """
Rscript install_dependencies.R
"""

[tasks.check]
description = "Validate the structure of the input files"
cmd = """
Rscript -e "sandpaper::check_lesson()"
"""

[tasks.build]
description = "build and validate lesson"
cmd = """
Rscript -e "sandpaper::build_lesson()"
"""

[tasks.serve]
description = "Serve the lesson"
cmd = """
Rscript -e "sandpaper::serve()"
"""

[tasks.start]
description = "Install R dependencies and serve site"
depends-on = ["install-requirements", "serve"]

[dependencies]
git = ">=2.49.0,<3"
r = ">=4.4,<4.5"
pandoc = ">=3.6.4,<4"
cxx-compiler = ">=1.9.0,<2"
zlib = ">=1.3.1,<2"
r-xml2 = ">=1.3.8,<2"
r-knitr = ">=1.50,<2"
r-usethis = ">=3.1.0,<4"
r-stringi = ">=1.8.7,<2"
r-fastmap = ">=1.2.0,<2"
r-memoise = ">=2.0.1,<3"
r-sass = ">=0.4.10,<0.5"
r-renv = ">=1.1.4,<2"
r-crayon = ">=1.5.3,<2"
r-brio = ">=1.1.5,<2"
r-fansi = ">=1.0.6,<2"
r-systemfonts = ">=1.2.1,<2"
r-fontawesome = ">=0.5.3,<0.6"
r-tibble = ">=3.2.1,<4"
r-pkgdown = ">=2.1.1,<3"
r-commonmark = ">=1.9.5,<2"
r-assertthat = ">=0.2.1,<0.3"
r-promises = ">=1.3.2,<2"
r-servr = ">=0.32,<0.33"
r-xslt = ">=1.5.1,<2"
